In [1]:
import numpy as np
import pandas as pd

In [2]:
credict_cb = pd.read_csv('./data/credit_card_balance.csv')

In [3]:
credict_cb = credict_cb.set_index(credict_cb.columns[1])
credict_cb = credict_cb.drop('SK_ID_PREV',axis=1)
print(credict_cb.shape)

(3840312, 21)

In [4]:
credict_cb.head()

,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
378907,-6,56.970,135000,0.0,877.5,0.0,877.5,1700.325,1800.0,1800.0,...,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
363914,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.000,2250.0,2250.0,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
371185,-7,31815.225,450000,0.0,0.0,0.0,0.0,2250.000,2250.0,2250.0,...,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
337855,-4,236572.110,225000,2250.0,2250.0,0.0,0.0,11795.760,11925.0,11925.0,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
126868,-1,453919.455,450000,0.0,11547.0,0.0,11547.0,22924.890,27000.0,27000.0,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0

In [5]:
%run ./code/label_encoder.py
credict_cb = credict_cb.groupby(credict_cb.index).last()
credict_cb = label_encoder(credict_cb)
credict_cb.shape

(103558, 21)

In [6]:
credict_cb.to_csv('./data/data_procesada/credict_cb_1.csv')